### ISSUE TITLE
Victory Point Tracking

### ISSUE THREAD

**Issue by pakirby1** [pakirby1/DialControl#110]
# Overview
Allow the user to track victory points.  The score should be persisted to CoreData similar to `squadData.favorite` updates.

## Tasks

- [ ] Update CoreData
  - [ ] Add victoryPoints entity
    - [ ] Name: victoryPoints
    - [ ] Type: Integer 32
    - [ ] Default Value: 0
- [ ] Update SquadData+CoreDataProperties.swift
  - [ ] @NSManaged public var victoryPoints: Int
- [ ] Update Redux_SquadView_Old.swift
  - [ ] Update ObjectiveScoreView
    - [ ] Update VectorImageButton to increment score
    - [ ] Update VectorImageButton to decrement score
- [ ] Update UI
  - [ ] Move buttons & score to the center of the view
